import DeleteUser from "@/app/components/DeleteUser";
import WithAuth from "@/app/middleware/withAuth";
import { getSession } from "@/app/session/getSession";
import JoinChat from "./components/JoinChat";
import NavbarChat from "./components/NavbarChat";

export const metadata = {
  title: "Live Chat",
  description: "Generated by create next app",
};

const Dashboard = async () => {
  const session = await getSession();

  return (
    <div className="overflow-x-hidden">
      <NavbarChat session={session} />
      <JoinChat session={session} />
      <div>{/* <DeleteUser email={session?.user.email} /> */}</div>
    </div>
  );
};

export default Dashboard;
