import NavbarComponent from "@/app/components/NavbarComponents";
import WithAuth from "@/app/middleware/withAuth";
import { getSession } from "@/app/session/getSession";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Dashboard = async () => {
  const session = await getSession();

  return (
    <div>
      <WithAuth session={session}>
        <NavbarComponent session={session} />
        <div>
          <h1>
            Selamat datang <b className="font-bold">{session?.user.name}</b>
          </h1>
          {/* <LogoutButton /> */}
        </div>
      </WithAuth>
    </div>
  );
};

export default Dashboard;
